version: '3.4'
services:
  fuseki:
    image: twalmsley/aosd-fuseki:latest
    container_name: fuseki
    hostname: fuseki
    ports:
      - 3030:3030
    volumes:
      - ./databases:/fuseki/run/databases
      - ./configuration:/fuseki/run/configuration
      - ./logs:/fuseki/run/logs
